### PR TITLE
feat: Add Post Endpoints and Migrations

### LINKED ISSUE #11: Setup Database Migration
As a developer I want my database to stay in sync with the code base I am working on.

Acceptance Criteria:
- When a developer runs the API application with the "--migrate" flag the database schema is synced with the migrations defined in that code revision. 
- When a developer runs the API application with the "--seed" flag the database is seeded with a test data set defined in the app.

**Task List:**
- [x] Replace meriadb lib with Knex JS /Connor
- [x] Setup app to run migrations when a "--migrate" flag is provided /Kevin
- [x] Setup app to run seed data when a "--seed" flag is provided. /Alec

### LINKED ISSUE #19: Implement POST v1/posts to Create a Post
As a content creator, I want to submit an image URL and a title so that it will show up on the frontpage and allow me to share my pictures with the world.

Acceptance Criteria:
- When a request is made against the POST v1/post endpoint with a JSON request body with an image URL and a post title the created resource with the created ID is sent back to the client with a success status code.  
- When an invalid POST request is made against the /v1/posts endpoint an error code is returned. (In the 400-499 HTTP response code.)

**Tasks:**
- [x] Create posts model. /Kevin (Cancelled)
- [x] Create posts table. /Kevin
- [x] Create controller for saving posts. /Connor
- [x] Create the route for POST /v1/posts /Connor

### LINKED ISSUE #22: Implement GET v1/posts endpoint
As a business user I want to persist post data so that I can retrieve it later for future use.

**Acceptance Criteria:**
- When a GET request is made against the /v1/posts endpoint a JSON document is returned with a collection of objects with the post title, id, and image url. 
- When an invalid GET request is made against the /v1/posts endpoint an error code is returned. (In the 400-499 HTTP response code.)

**Tasks:**
- [x] Create posts model. (Cancelled)
- [x] Create posts table.
- [x] Create controller for getting posts.
- [x] Create the route for GET /v1/posts

### PR DESCRIPTION
**Pull request by 3dxp**
Add the following endpoints to the API:
- GET /api/v1/posts
- GET /api/v1/posts/{id}
- POST /api/v1/posts

Added migration machinery to allow for
database migrations to be ran by adding
a flag when running the api server.

#22, #19, #11

### CODE REVIEW

**Comment by 3dxp** [comment]
NOTE: A few things still need to be added and or fixed:
- Image URL validation
- Error Handling
- Data Seeding

**Comment by zxkevin** [comment]
I helped paired programmed this. Added image URL validation

**Review by ckhorra1 — APPROVED** [review]
Looks good thank you!

**Review by ahassani93 — APPROVED** [review]
Thanks!

**Review by zxkevin — APPROVED** [review]
Tested locally and working. All things look good!

**Review by acampb65 — APPROVED** [review]
Pair programmed seed data. Tested locally to confirm everything works.

**Review by toxictortoise — APPROVED** [review]

**Pull request merged**
